
POSTGRES_USER: sweeft
POSTGRES_PASSWORD: sweeft
POSTGRES_URL: jdbc:postgresql://192.168.191.58:5432/common


REALM: sweeft
KEYCLOAK_HOST: http://192.168.191.58:8081
KEYCLOAK_ADMIN_USER: admin
KEYCLOAK_ADMIN_PASSWORD: admin
KEYCLOAK_CLIENT: sweeft-api-gateway

COMMON_PORT: 8080